### ISSUE TITLE
ENTREVISTA

### ISSUE THREAD

**Issue by AricelCastro** [SistemasTecTlaxiaco/actividad-7-practica-de-entrevista-equipo-naa#1]
[entrevistaaa.pdf](https://github.com/user-attachments/files/17566778/entrevistaaa.pdf)

**Comment by KevCH24** [comment]
29/30
LE FALTA DETALLAR MAS SU INFORMACION RECAVADA ,Y JUSTIFICAR SU TEXTO DEL PROYECTO

**Comment by josealfredo79** [comment]
bien hecho y revisado...
